version: "3.8"

services:
  backend:
    image: mishmainmo/mission5official:backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGODB_URI: "mongodb://mongo:27017/apihouses"
    networks:
      - metro_network

  frontend:
    image: mishmainmo/mission5official:frontend
    ports:
      - "3000:3000"
    networks:
      - metro_network

  mongo:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    networks:
      - metro_network

volumes:
  mongodata:

networks:
  metro_network:
    driver: bridge
